baseURL: 'https://mafelp.github.io/hugo-bootstrap-shortcodes/'
languageCode: 'en-us'
title: 'hugo-bootstrap-shortcodes Documentation'

theme:
  - 'hugo-bootstrap-shortcodes'

module:
  mounts:
    - source: 'assets'
      target: 'assets'
    - source: 'assets/sass'
      target: 'assets/sass'
    - source: 'assets/fonts'
      target: 'assets/fonts'
