baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'My New Hugo Site'

theme:
  - 'hugo-bootstrap-shortcodes'

module:
  mounts:
    - source: 'assets'
      target: 'assets'
    - source: 'assets/sass'
      target: 'assets/sass'
    - source: 'assets/fonts'
      target: 'assets/fonts'
